### ISSUE TITLE
[SvelteKit] build breaks when `document` is used in a component

### ISSUE THREAD

**Issue by macmillen** [vitebook/vitebook#33]
Currently the `vitebook:build` throws an error when `document` is used within a component inside a story.

```
> vitebook build

vitebook@0.21.1

🚨 Rendering 15 pages...

 ReferenceError: document is not defined
    at /home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:7643:16
    at Object.$$render (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:352:22)
    at Object.default (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:7671:60)
    at /home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:1142:36
    at Object.$$render (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:352:22)
    at /home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:7669:53
    at Object.$$render (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:352:22)
    at Object.default (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:1040:85)
    at /home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:1027:192
    at Object.$$render (/home/milln/projects/lettranslate-web-app/.vitebook/dist/server/entry-server.cjs:352:22)
```

Current workaround:

``` js
import { JSDOM } from "jsdom";

const dom = new JSDOM();
global.document = dom.window.document;
global.Node = dom.window.Node;
```

**Comment by mihar-22** [comment]
This is expected because it's rendered server-side. Ensure your components are SSR friendly by not using any browser API's  outside of `onMounted`, or without checking if you're in the browser via...

```ts
import { browser } from '$app/env';

if (browser) {
  // ...
}
```

**Comment by henriquehbr** [comment]
@mihar-22 I'm facing the exact same problem, but with Svelte, more specifically, i'm trying to include [this](https://github.com/henriquehbr/svelte-typewriter/tree/dev) library on a Vitebook

I tried commenting out most of the component code, to the point where only a single "Hello World!" `<p>` was left, but still wasn't able to get it working, even without any reference to `document` the error is still appearing, removing `.vitebook/.cache` and `.vitebook/.temp` also didn't solved the problem

Currently, my Vitebook config is looking like this:

```js
import { svelte } from '@sveltejs/vite-plugin-svelte'
import { clientPlugin, defineConfig } from '@vitebook/client/node';
import { defaultThemePlugin } from '@vitebook/theme-default/node';

export default defineConfig({
  include: ['src/stories/*.story.svelte'],
  plugins: [
    clientPlugin({ appFile: 'App.svelte' }),
    defaultThemePlugin(),
    svelte({
        compilerOptions: {
            hydratable: true
        },
        extensions: ['.svelte']
    })
  ],
  site: {
    title: '',
    description: '',
    baseUrl: '/svelte-typewriter/',
    /** @type {(import('@vitebook/theme-default/node').DefaultThemeConfig} */
    theme: {},
  },
});
```
