### ISSUE TITLE
Unable to change configDir

### ISSUE THREAD

**Issue by OwenVey** [vitebook/vitebook#40]
I tried changing my `configDir` to `docs` and when running `vitebook dev`, I get the following error:
```
 Error: ENOENT: no such file or directory, lstat '/Users/tkmam1x/Desktop/jarvis-components-ts/.vitebook'
    at Object.lstatSync (node:fs:1516:3)
    at Object.lstatSync (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:12004:72)
    at resolveRelativePath (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:17940:134)
    at resolveUserAppConfig (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:18997:19)
    at resolveApp (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:18932:37)
    at devCommand (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:19010:21)
    at CAC.runDevCommand (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:19047:3)
    at CAC.runMatchedCommand (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:17262:34)
    at CAC.parse (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:17189:12)
    at file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:19085:9 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/tkmam1x/Desktop/jarvis-components-ts/.vitebook'
} 
```

It looks like Vitebook is still looking for the default `.vitebook` folder. I tried deleting my `.cache` and `.temp` folder and reinstall `node_modules` in case something was getting cached but no success there.

I'm using version `0.23.0` and my `config.ts` looks like:
```ts
import { clientPlugin, defineConfig } from '@vitebook/client/node';
import { vueMarkdownPlugin } from '@vitebook/markdown-vue/node';
import { vuePlugin } from '@vitebook/vue/node';
import { defaultThemePlugin, DefaultThemeConfig } from '@vitebook/theme-default/node';

export default defineConfig<DefaultThemeConfig>({
  srcDir: 'src/stories',
  configDir: 'docs',
  include: ['src/**/*.md', 'src/**/*.story.vue'],
  plugins: [vueMarkdownPlugin(), vuePlugin({ appFile: 'App.vue' }), clientPlugin(), defaultThemePlugin()],
  site: {
    title: 'Jarvis Components',
    description: '',
    theme: {
      sidebar: {
        style: 'docs',
      },
    },
    head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '../favicon.svg' }]],
  },
});
```

Let me know if you need more information!

**Comment by OwenVey** [comment]
Same thing is happening with the build and preview commands where I need to specify `--configDir docs` in the script command or Vitebook will look for `.vitebook` and crash.

**Comment by mihar-22** [comment]
This is by design because we can't infer where the configuration file is at the time you run CLI commands since we haven't loaded the configuration file yet. Here's a different approach towards the same outcome that'd be more Vitebook-like:

1. `npm init vitebook docs` (if folder already exists just copy paste contents of your `docs` dir into `docs/.vitebook`, ensure a `docs/src` dir also exists).

2. Update Vitebook scripts in `package.json` as follows


```json
{
  "scripts": {
    "vitebook:dev": "vitebook dev docs",
    "vitebook:build": "vitebook build docs",
    "vitebook:preview": "vitebook preview docs"
  }
}
```

3. Make sure to bump Vitebook packages to `0.23.1` since I just fixed the preview command to support a root directory as shown in the example.

Hope that resolves what you're looking for 😄

**Comment by mihar-22** [comment]
I should remove the `configDir` option from the Vitebook configuration options since it's misleading.

**Comment by OwenVey** [comment]
Ahh that makes sense. Agreed that it's a good idea to remove `configDir` from the docs. The reason I wanted to do this in the first place is because I couldn't find a way for Vitebook _not_ to use my root `vite.config.ts` file when building the docs. I have a build section in my Vite config for building the actual component library that was causing the following error:
```
Error: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
```
I messed around with Vite's [Conditional Config](https://vitejs.dev/config/#conditional-config) but it was ultimately not possible to distinguish between my build command and Vitebook's build command and was a bit messy for my liking.

So now my folder structure is:
```
docs/
├─ .vitebook/
│  ├─ vite.config.ts (for building docs) 
src/
├─ components/
vite.config.ts (for building my component lib)
```
which is working for my use case.

I might have missed some config option in the docs about this so let me know if there's a better way to accomplish this!

Thanks again!

**Comment by OwenVey** [comment]
Hm, something doesn't seem to be playing nicely when building. Running the dev server starts up fine however. Here is my folder structure a little more detailed:

```
docs/
├── .vitebook/
│   └── config.ts
├── stores/
│   ├── Button.story.vue
│   ├── Input.story.vue
│   └── ...
└── vite.config.ts
src/
└── components/
    ├── Button.vue
    ├── Input.vue
    └── ...
vite.config.ts
```

In my `config.ts`, I have the following:
```ts
export default defineConfig<DefaultThemeConfig>({
  srcDir: 'stories',
  include: ['stories/*.story.vue'],
  plugins: [
    vueMarkdownPlugin(),
    vuePlugin({ appFile: 'App.vue' }),
    clientPlugin(),
    defaultThemePlugin(),
  ],
  site: {
    title: 'Jarvis Components',
    description: '',
    theme: {
      sidebar: {
        style: 'docs',
      },
    },
    head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '../favicon.svg' }]],
  },
});
```
This works perfect for dev, but when I publish I'm getting the following error:
```ps
 Error: ENOENT: no such file or directory, lstat '/Users/tkmam1x/Desktop/stories'
    at Object.realpathSync (node:fs:2490:7)
    at resolvePageImports (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:18413:22)
    at build2 (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:18290:27)
    at async buildCommand (file:///Users/tkmam1x/Desktop/jarvis-components-ts/node_modules/@vitebook/core/dist/node/cli/run.js:19008:3) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/tkmam1x/Desktop/stories'
} 
```

I inserted some logs in `node_modules/@vitebook/core/dist/node/cli/run.js` and noticed `app.dirs.root.relative()` was returning as `../stories/Button.story.vue` which doesn't seem correct. I believe it should be `docs/stories/Button.story.vue` but was unable to figure out whether the problem was with my configuration or a bug.
