### ISSUE TITLE
Installation issue with svelte or sveltekit

### ISSUE THREAD

**Issue by MagedEWilliam** [vitebook/vitebook#51]
Environment:
Windows 11 64bit

steps:
`npm init svelte@next my-app`
`cd my-app`
`npm install`
`npm init vitebook`
`? Select a framework: ...
svelte`

`? Select a theme: ...
blank`

`? Features: ...
tailwind`

now when running the following i get an error:
```npm run vitebook:dev```

<details>
  <summary>Error</summary>
  
> vitebook@0.0.1 vitebook:dev
> vitebook dev

 > error: The entry point "E:/Projects/vitebook/.vitebook/config.js" cannot be marked as external

 Error: Build failed with 1 error:
error: The entry point "E:/Projects/vitebook/.vitebook/config.js" cannot be marked as external
    at failureErrorWithLog (E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1475:15)
    at E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1133:28
    at runOnEndCallbacks (E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:923:63)
    at buildResponseToResult (E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1131:7)
    at E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1240:14
    at E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:611:9
    at handleIncomingPacket (E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:708:9)
    at Socket.readFromStdout (E:\Projects\vitebook\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:578:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The entry point "E:/Projects/vitebook/.vitebook/config.js" cannot be marked as external'
    }
  ],
  warnings: []
}
 </details>

**Comment by mihar-22** [comment]
Try setting the `theme` to `default` to see if it resolves the issue.

**Comment by MagedEWilliam** [comment]
Setting theme to default lead to the same error.

I tested on linux subsystem, and it works fine tho.
