### ISSUE TITLE
Error on windows 11 with powershell and node17.7

### ISSUE THREAD

**Issue by Myrmod** [vitebook/vitebook#60]
Hello,

this seems more like a `vite` issue, though this project has this problem as well.

.I tried to run https://github.com/Myrmod/svelte-babylon `npm run vitebook:dev` on windows 11 with powershell and node17.7. 
The following error occurs:

```sh
PS C:\Users\pasca\Desktop\test\svelte-babylon> npm run vitebook:dev  

> svelte-babylon@0.11.0 vitebook:dev
> vitebook dev

 > error: The entry point "C:/Users/pasca/Desktop/test/svelte-babylon/.vitebook/config.js" cannot be marked as external


 Error: Build failed with 1 error:
error: The entry point "C:/Users/pasca/Desktop/test/svelte-babylon/.vitebook/config.js" cannot be marked as external
    at failureErrorWithLog (C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1475:15)
    at C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1133:28
    at runOnEndCallbacks (C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:923:63)
    at buildResponseToResult (C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1131:7)
    at C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:1240:14
    at C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:611:9
    at handleIncomingPacket (C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:708:9)
    at Socket.readFromStdout (C:\Users\pasca\Desktop\test\svelte-babylon\node_modules\@vitebook\core\node_modules\esbuild\lib\main.js:578:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: null,
      notes: [],
      pluginName: '',
      text: 'The entry point "C:/Users/pasca/Desktop/test/svelte-babylon/.vitebook/config.js" cannot be marked as external'
    }
  ],
  warnings: []
}
```

I am currently trying to fix this problem in the afforementioned library. If you got any tipps, I would be happy to hear them.

Best regards

**Comment by whoisYeshua** [comment]
looks like duplicate of https://github.com/vitebook/vitebook/issues/20

**Comment by Myrmod** [comment]
> 

seems like it yes, I must've overlooked the issue #20
