### ISSUE TITLE
Not working with yarn@berry

### ISSUE THREAD

**Issue by Seo-Rii** [vitebook/vitebook#76]
I created project with svelte template.
When I run the example code with yarn berry, the dependency `@vitebook/client` did not install with the following error:
```
# This file contains the result of Yarn building a package (@vitebook/client@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:0.23.5)
# Script name: postinstall

~\.pnp.cjs:10382
  return Object.defineProperties(new Error(message), {
                                 ^

Error: @vitebook/client tried to access upath, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: upath (via "upath\package.json")
Required by: @vitebook/client@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:0.23.5 (via ~\.yarn\unplugged\@vitebook-client-virtual-4d0d0b9e21\node_modules\@vitebook\client\.scripts\patch-just-it.js)

    at makeError (~\.pnp.cjs:10382:34)
    at resolveToUnqualified (~\.pnp.cjs:11296:21)
    at Object.resolveToUnqualified (~\.pnp.cjs:11440:26)
    at resolve$1 (file:///~/.pnp.loader.mjs:207:31)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

Example works well with yarn classic.

**Comment by julianlionti** [comment]
Same problem
