### ISSUE TITLE
Example React build fails

### ISSUE THREAD

**Issue by cesargdm** [vitebook/vitebook#84]
Using the example at https://stackblitz.com/github/vitebook/vitebook/tree/main/examples/react?file=package.json the `vitebook:build` script fails with:

```
⠼ Rendering 3 pages...'useState' is not exported by .vitebook/.cache/deps_build-5c78b490/react.js, imported by src/Button/Button.story.tsx
file: /home/projects/qgniywqbg.github/src/Button/Button.story.tsx:8:0
 6:   EventsAddon,
 7: } from '@vitebook/preact/addons';
 8: import { useState } from 'react';
    ^
 9: 
10: import Button from './Button';
🚨 Rendering 3 pages...

 Error: 'useState' is not exported by .vitebook/.cache/deps_build-5c78b490/react.js, imported by src/Button/Button.story.tsx
    at error (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:1888:30)
    at Module.error (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:12441:16)
    at Module.traceVariable (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:12800:29)
    at ModuleScope.findVariable (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:11452:39)
    at FunctionScope.findVariable (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:6385:38)
    at ChildScope.findVariable (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:6385:38)
    at Identifier.bind (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:7452:40)
    at CallExpression.bind (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:5282:23)
    at CallExpression.bind (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:8948:15)
    at VariableDeclarator.bind (file:///home/projects/qgniywqbg.github/node_modules/rollup/dist/es/shared/rollup.js:5282:23) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/home/projects/qgniywqbg.github/src/Button/Button.story.tsx',
  pos: 138,
  loc: {
    column: 0,
    file: '/home/projects/qgniywqbg.github/src/Button/Button.story.tsx',
    line: 8
  },
  frame: ' 6:   EventsAddon,\n' +
    " 7: } from '@vitebook/preact/addons';\n" +
    " 8: import { useState } from 'react';\n" +
    '    ^\n' +
    ' 9: \n' +
    "10: import Button from './Button';",
  watchFiles: [
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/entry-client.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/context/context-keys.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/createRouter.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/preflight.css',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/App.svelte',
    '/home/projects/qgniywqbg.github/.vitebook/.cache/deps_build-5c78b490/svelte.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/package.json',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/router/history/memory.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/router/router.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentRoute.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/pages.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/siteOptions.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/theme.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/client/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/composables/useUpdateHead.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/siteLang.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/DefaultNotFound.svelte',
    '/home/projects/qgniywqbg.github/.vitebook/.cache/deps_build-5c78b490/svelte_store.js',
    '/home/projects/qgniywqbg.github/.vitebook/.cache/deps_build-5c78b490/svelte_internal.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/context/useSSRContext.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentPageHead.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/localizedSiteOptions.js',
    '/:virtual/vitebook/pages',
    '/:virtual/vitebook/site',
    '/home/projects/qgniywqbg.github/.vitebook/theme/index.ts',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/package.json',
    '\x00vite/preload-helper',
    '/home/projects/qgniywqbg.github/src/Button/Button.story.tsx',
    '/home/projects/qgniywqbg.github/src/Button/docs.md',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/PreactPageView.svelte',
    '/home/projects/qgniywqbg.github/node_modules/preact/package.json',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/package.json',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/ssr.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/HeadConfig.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/LocaleConfig.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/MarkdownPageMeta.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/Page.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/PageMeta.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/SiteOptions.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/Theme.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/types/utils.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/date.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/head.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/html.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/json.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/locale.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/string.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/support.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/unit.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/core/dist/shared/utils/url.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentPageDescription.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentPageTitle.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentRouteLocale.js',
    '/home/projects/qgniywqbg.github/node_modules/preact/dist/preact.module.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/PreactAdapter.svelte',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/router/types.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/context/useAppContext.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/context/useRouter.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentMarkdownPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/currentMarkdownPageMeta.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/variants.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/stores/withBaseUrl.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/ClientOnly.svelte',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/OutboundLink.svelte',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/PageView.svelte',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/Variant.svelte',
    '/home/projects/qgniywqbg.github/.vitebook/App.tsx',
    '/home/projects/qgniywqbg.github/src/Button/Button.tsx',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/types/ClientPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/types/ClientTheme.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/types/MarkdownPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/types/SveltePage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/utils/isLoadedMarkdownPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/utils/isMarkdownPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/shared/utils/isSveltePage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/OutboundLink.svelte?svelte&type=style&lang.css',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/components/App.svelte',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/shared/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/components/OutboundLink.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/components/Variant.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/addons/index.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/theme-default/package.json',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/theme-default/dist/client/index.js',
    '/home/projects/qgniywqbg.github/node_modules/preact/hooks/package.json',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/theme-default/dist/client/polyfills/focus-visible.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/shared/types/PreactPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/shared/utils/isLoadedPreactPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/shared/utils/isPreactPage.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/hooks/useVariants.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/addons/Addon.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/addons/ControlsAddon.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/preact/dist/client/addons/EventsAddon.js',
    '/home/projects/qgniywqbg.github/node_modules/preact/hooks/dist/hooks.module.js',
    '/home/projects/qgniywqbg.github/node_modules/@vitebook/client/dist/client/addons/index.js',
    '/home/projects/qgniywqbg.github/node_modules/preact/compat/package.json',
    ... 148 more items
  ]
} 
```

Even with a simple `index.md`

```md
# Hello world
````

The build error we can get is:

```
$ vitebook build
vitebook@0.100.2

🚨 Rendering 1 pages...

 ReferenceError: require is not defined
    at eval (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:3192:27)
    at Object.$$render (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:343:22)
    at eval (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:3229:65)
    at Object.$$render (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:343:22)
    at eval (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:1059:83)
    at Object.$$render (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:343:22)
    at eval (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:1068:45)
    at Object.$$render (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:343:22)
    at eval (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:2587:50)
    at Object.$$render (file:///home/projects/github-me4ejx/.vitebook/dist/server/entry-server.js:343:22)
```

**Comment by mihar-22** [comment]
Should be fixed now, thanks for reporting :)

**Comment by cesargdm** [comment]
Thank you @mihar-22
